version: "3.6"

services:
  indexer:
    image: ghcr.io/dipdup-io/starknet-indexer:master
    build:
        dockerfile: build/Dockerfile
        context: .
    env_file:
      - .env
    restart: always
    ports:
      - 127.0.0.1:7779:7779
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-changeme}
    depends_on:
      - db
      - hasura
    logging: &straknet-dipdup-logging
      options:
        max-size: 10m
        max-file: "5"
    volumes:
      - /etc/starknet:/etc/starknet

  db:
    image: postgres:15
    restart: always
    volumes:
      - db:/var/lib/postgres/data
      - /etc/postgresql/postgresql.conf:/etc/postgresql/postgresql.conf
    ports:
      - 127.0.0.1:5432:5432
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST:-db}
      - POSTGRES_USER=${POSTGRES_USER:-dipdup}
      - POSTGRES_DB=${POSTGRES_DB:-starknet}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-changeme}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dipdup -d starknet"]
      interval: 10s
      timeout: 5s
      retries: 5
    logging: *straknet-dipdup-logging
    command:
      - "postgres"
      - "-c"
      - "config_file=${POSTGRES_CONFIG:-/etc/postgresql/postgresql.conf}"

  hasura:
    image: hasura/graphql-engine:v2.22.0
    ports:
      - 127.0.0.1:8080:8080
    restart: always
    environment:
      - HASURA_GRAPHQL_DATABASE_URL=postgres://dipdup:${POSTGRES_PASSWORD:-changeme}@db:5432/starknet
      - HASURA_GRAPHQL_ENABLE_CONSOLE=true
      - HASURA_GRAPHQL_DEV_MODE=true
      - HASURA_GRAPHQL_ENABLED_LOG_TYPES=startup, http-log, webhook-log, websocket-log, query-log
      - HASURA_GRAPHQL_ADMIN_SECRET=${ADMIN_SECRET:-changeme}
      - HASURA_GRAPHQL_UNAUTHORIZED_ROLE=user
    logging: *straknet-dipdup-logging

volumes:
  db: