// Code generated by MockGen. DO NOT EDIT.
// Source: internal.go
//
// Generated by this command:
//
//	mockgen -source=internal.go -destination=mock/internal.go -package=mock -typed
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	storage "github.com/dipdup-io/starknet-indexer/internal/storage"
	storage0 "github.com/dipdup-net/indexer-sdk/pkg/storage"
	gomock "go.uber.org/mock/gomock"
)

// MockIInternal is a mock of IInternal interface.
type MockIInternal struct {
	ctrl     *gomock.Controller
	recorder *MockIInternalMockRecorder
	isgomock struct{}
}

// MockIInternalMockRecorder is the mock recorder for MockIInternal.
type MockIInternalMockRecorder struct {
	mock *MockIInternal
}

// NewMockIInternal creates a new mock instance.
func NewMockIInternal(ctrl *gomock.Controller) *MockIInternal {
	mock := &MockIInternal{ctrl: ctrl}
	mock.recorder = &MockIInternalMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIInternal) EXPECT() *MockIInternalMockRecorder {
	return m.recorder
}

// CursorList mocks base method.
func (m *MockIInternal) CursorList(ctx context.Context, id, limit uint64, order storage0.SortOrder, cmp storage0.Comparator) ([]*storage.Internal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CursorList", ctx, id, limit, order, cmp)
	ret0, _ := ret[0].([]*storage.Internal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CursorList indicates an expected call of CursorList.
func (mr *MockIInternalMockRecorder) CursorList(ctx, id, limit, order, cmp any) *MockIInternalCursorListCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CursorList", reflect.TypeOf((*MockIInternal)(nil).CursorList), ctx, id, limit, order, cmp)
	return &MockIInternalCursorListCall{Call: call}
}

// MockIInternalCursorListCall wrap *gomock.Call
type MockIInternalCursorListCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIInternalCursorListCall) Return(arg0 []*storage.Internal, arg1 error) *MockIInternalCursorListCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIInternalCursorListCall) Do(f func(context.Context, uint64, uint64, storage0.SortOrder, storage0.Comparator) ([]*storage.Internal, error)) *MockIInternalCursorListCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIInternalCursorListCall) DoAndReturn(f func(context.Context, uint64, uint64, storage0.SortOrder, storage0.Comparator) ([]*storage.Internal, error)) *MockIInternalCursorListCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Filter mocks base method.
func (m *MockIInternal) Filter(ctx context.Context, flt []storage.InternalFilter, opts ...storage.FilterOption) ([]storage.Internal, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, flt}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Filter", varargs...)
	ret0, _ := ret[0].([]storage.Internal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Filter indicates an expected call of Filter.
func (mr *MockIInternalMockRecorder) Filter(ctx, flt any, opts ...any) *MockIInternalFilterCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, flt}, opts...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Filter", reflect.TypeOf((*MockIInternal)(nil).Filter), varargs...)
	return &MockIInternalFilterCall{Call: call}
}

// MockIInternalFilterCall wrap *gomock.Call
type MockIInternalFilterCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIInternalFilterCall) Return(arg0 []storage.Internal, arg1 error) *MockIInternalFilterCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIInternalFilterCall) Do(f func(context.Context, []storage.InternalFilter, ...storage.FilterOption) ([]storage.Internal, error)) *MockIInternalFilterCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIInternalFilterCall) DoAndReturn(f func(context.Context, []storage.InternalFilter, ...storage.FilterOption) ([]storage.Internal, error)) *MockIInternalFilterCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetByID mocks base method.
func (m *MockIInternal) GetByID(ctx context.Context, id uint64) (*storage.Internal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*storage.Internal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockIInternalMockRecorder) GetByID(ctx, id any) *MockIInternalGetByIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockIInternal)(nil).GetByID), ctx, id)
	return &MockIInternalGetByIDCall{Call: call}
}

// MockIInternalGetByIDCall wrap *gomock.Call
type MockIInternalGetByIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIInternalGetByIDCall) Return(arg0 *storage.Internal, arg1 error) *MockIInternalGetByIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIInternalGetByIDCall) Do(f func(context.Context, uint64) (*storage.Internal, error)) *MockIInternalGetByIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIInternalGetByIDCall) DoAndReturn(f func(context.Context, uint64) (*storage.Internal, error)) *MockIInternalGetByIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetDeployedContracts mocks base method.
func (m *MockIInternal) GetDeployedContracts(arg0 context.Context, arg1 []byte) ([]storage.DeployedContract, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeployedContracts", arg0, arg1)
	ret0, _ := ret[0].([]storage.DeployedContract)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDeployedContracts indicates an expected call of GetDeployedContracts.
func (mr *MockIInternalMockRecorder) GetDeployedContracts(arg0, arg1 any) *MockIInternalGetDeployedContractsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeployedContracts", reflect.TypeOf((*MockIInternal)(nil).GetDeployedContracts), arg0, arg1)
	return &MockIInternalGetDeployedContractsCall{Call: call}
}

// MockIInternalGetDeployedContractsCall wrap *gomock.Call
type MockIInternalGetDeployedContractsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIInternalGetDeployedContractsCall) Return(arg0 []storage.DeployedContract, arg1 error) *MockIInternalGetDeployedContractsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIInternalGetDeployedContractsCall) Do(f func(context.Context, []byte) ([]storage.DeployedContract, error)) *MockIInternalGetDeployedContractsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIInternalGetDeployedContractsCall) DoAndReturn(f func(context.Context, []byte) ([]storage.DeployedContract, error)) *MockIInternalGetDeployedContractsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// IsNoRows mocks base method.
func (m *MockIInternal) IsNoRows(err error) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsNoRows", err)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsNoRows indicates an expected call of IsNoRows.
func (mr *MockIInternalMockRecorder) IsNoRows(err any) *MockIInternalIsNoRowsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsNoRows", reflect.TypeOf((*MockIInternal)(nil).IsNoRows), err)
	return &MockIInternalIsNoRowsCall{Call: call}
}

// MockIInternalIsNoRowsCall wrap *gomock.Call
type MockIInternalIsNoRowsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIInternalIsNoRowsCall) Return(arg0 bool) *MockIInternalIsNoRowsCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIInternalIsNoRowsCall) Do(f func(error) bool) *MockIInternalIsNoRowsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIInternalIsNoRowsCall) DoAndReturn(f func(error) bool) *MockIInternalIsNoRowsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// LastID mocks base method.
func (m *MockIInternal) LastID(ctx context.Context) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LastID", ctx)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LastID indicates an expected call of LastID.
func (mr *MockIInternalMockRecorder) LastID(ctx any) *MockIInternalLastIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LastID", reflect.TypeOf((*MockIInternal)(nil).LastID), ctx)
	return &MockIInternalLastIDCall{Call: call}
}

// MockIInternalLastIDCall wrap *gomock.Call
type MockIInternalLastIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIInternalLastIDCall) Return(arg0 uint64, arg1 error) *MockIInternalLastIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIInternalLastIDCall) Do(f func(context.Context) (uint64, error)) *MockIInternalLastIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIInternalLastIDCall) DoAndReturn(f func(context.Context) (uint64, error)) *MockIInternalLastIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// List mocks base method.
func (m *MockIInternal) List(ctx context.Context, limit, offset uint64, order storage0.SortOrder) ([]*storage.Internal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, limit, offset, order)
	ret0, _ := ret[0].([]*storage.Internal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockIInternalMockRecorder) List(ctx, limit, offset, order any) *MockIInternalListCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockIInternal)(nil).List), ctx, limit, offset, order)
	return &MockIInternalListCall{Call: call}
}

// MockIInternalListCall wrap *gomock.Call
type MockIInternalListCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIInternalListCall) Return(arg0 []*storage.Internal, arg1 error) *MockIInternalListCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIInternalListCall) Do(f func(context.Context, uint64, uint64, storage0.SortOrder) ([]*storage.Internal, error)) *MockIInternalListCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIInternalListCall) DoAndReturn(f func(context.Context, uint64, uint64, storage0.SortOrder) ([]*storage.Internal, error)) *MockIInternalListCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Save mocks base method.
func (m_2 *MockIInternal) Save(ctx context.Context, m *storage.Internal) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "Save", ctx, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockIInternalMockRecorder) Save(ctx, m any) *MockIInternalSaveCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockIInternal)(nil).Save), ctx, m)
	return &MockIInternalSaveCall{Call: call}
}

// MockIInternalSaveCall wrap *gomock.Call
type MockIInternalSaveCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIInternalSaveCall) Return(arg0 error) *MockIInternalSaveCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIInternalSaveCall) Do(f func(context.Context, *storage.Internal) error) *MockIInternalSaveCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIInternalSaveCall) DoAndReturn(f func(context.Context, *storage.Internal) error) *MockIInternalSaveCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Update mocks base method.
func (m_2 *MockIInternal) Update(ctx context.Context, m *storage.Internal) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "Update", ctx, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockIInternalMockRecorder) Update(ctx, m any) *MockIInternalUpdateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockIInternal)(nil).Update), ctx, m)
	return &MockIInternalUpdateCall{Call: call}
}

// MockIInternalUpdateCall wrap *gomock.Call
type MockIInternalUpdateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIInternalUpdateCall) Return(arg0 error) *MockIInternalUpdateCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIInternalUpdateCall) Do(f func(context.Context, *storage.Internal) error) *MockIInternalUpdateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIInternalUpdateCall) DoAndReturn(f func(context.Context, *storage.Internal) error) *MockIInternalUpdateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
