// Code generated by MockGen. DO NOT EDIT.
// Source: transfer.go
//
// Generated by this command:
//
//	mockgen -source=transfer.go -destination=mock/transfer.go -package=mock -typed
//
// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	storage "github.com/dipdup-io/starknet-indexer/internal/storage"
	storage0 "github.com/dipdup-net/indexer-sdk/pkg/storage"
	gomock "go.uber.org/mock/gomock"
)

// MockITransfer is a mock of ITransfer interface.
type MockITransfer struct {
	ctrl     *gomock.Controller
	recorder *MockITransferMockRecorder
}

// MockITransferMockRecorder is the mock recorder for MockITransfer.
type MockITransferMockRecorder struct {
	mock *MockITransfer
}

// NewMockITransfer creates a new mock instance.
func NewMockITransfer(ctrl *gomock.Controller) *MockITransfer {
	mock := &MockITransfer{ctrl: ctrl}
	mock.recorder = &MockITransferMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockITransfer) EXPECT() *MockITransferMockRecorder {
	return m.recorder
}

// CursorList mocks base method.
func (m *MockITransfer) CursorList(ctx context.Context, id, limit uint64, order storage0.SortOrder, cmp storage0.Comparator) ([]*storage.Transfer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CursorList", ctx, id, limit, order, cmp)
	ret0, _ := ret[0].([]*storage.Transfer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CursorList indicates an expected call of CursorList.
func (mr *MockITransferMockRecorder) CursorList(ctx, id, limit, order, cmp any) *ITransferCursorListCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CursorList", reflect.TypeOf((*MockITransfer)(nil).CursorList), ctx, id, limit, order, cmp)
	return &ITransferCursorListCall{Call: call}
}

// ITransferCursorListCall wrap *gomock.Call
type ITransferCursorListCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *ITransferCursorListCall) Return(arg0 []*storage.Transfer, arg1 error) *ITransferCursorListCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *ITransferCursorListCall) Do(f func(context.Context, uint64, uint64, storage0.SortOrder, storage0.Comparator) ([]*storage.Transfer, error)) *ITransferCursorListCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *ITransferCursorListCall) DoAndReturn(f func(context.Context, uint64, uint64, storage0.SortOrder, storage0.Comparator) ([]*storage.Transfer, error)) *ITransferCursorListCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Filter mocks base method.
func (m *MockITransfer) Filter(ctx context.Context, flt []storage.TransferFilter, opts ...storage.FilterOption) ([]storage.Transfer, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, flt}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Filter", varargs...)
	ret0, _ := ret[0].([]storage.Transfer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Filter indicates an expected call of Filter.
func (mr *MockITransferMockRecorder) Filter(ctx, flt any, opts ...any) *ITransferFilterCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, flt}, opts...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Filter", reflect.TypeOf((*MockITransfer)(nil).Filter), varargs...)
	return &ITransferFilterCall{Call: call}
}

// ITransferFilterCall wrap *gomock.Call
type ITransferFilterCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *ITransferFilterCall) Return(arg0 []storage.Transfer, arg1 error) *ITransferFilterCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *ITransferFilterCall) Do(f func(context.Context, []storage.TransferFilter, ...storage.FilterOption) ([]storage.Transfer, error)) *ITransferFilterCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *ITransferFilterCall) DoAndReturn(f func(context.Context, []storage.TransferFilter, ...storage.FilterOption) ([]storage.Transfer, error)) *ITransferFilterCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetByID mocks base method.
func (m *MockITransfer) GetByID(ctx context.Context, id uint64) (*storage.Transfer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*storage.Transfer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockITransferMockRecorder) GetByID(ctx, id any) *ITransferGetByIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockITransfer)(nil).GetByID), ctx, id)
	return &ITransferGetByIDCall{Call: call}
}

// ITransferGetByIDCall wrap *gomock.Call
type ITransferGetByIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *ITransferGetByIDCall) Return(arg0 *storage.Transfer, arg1 error) *ITransferGetByIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *ITransferGetByIDCall) Do(f func(context.Context, uint64) (*storage.Transfer, error)) *ITransferGetByIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *ITransferGetByIDCall) DoAndReturn(f func(context.Context, uint64) (*storage.Transfer, error)) *ITransferGetByIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// IsNoRows mocks base method.
func (m *MockITransfer) IsNoRows(err error) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsNoRows", err)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsNoRows indicates an expected call of IsNoRows.
func (mr *MockITransferMockRecorder) IsNoRows(err any) *ITransferIsNoRowsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsNoRows", reflect.TypeOf((*MockITransfer)(nil).IsNoRows), err)
	return &ITransferIsNoRowsCall{Call: call}
}

// ITransferIsNoRowsCall wrap *gomock.Call
type ITransferIsNoRowsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *ITransferIsNoRowsCall) Return(arg0 bool) *ITransferIsNoRowsCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *ITransferIsNoRowsCall) Do(f func(error) bool) *ITransferIsNoRowsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *ITransferIsNoRowsCall) DoAndReturn(f func(error) bool) *ITransferIsNoRowsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// LastID mocks base method.
func (m *MockITransfer) LastID(ctx context.Context) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LastID", ctx)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LastID indicates an expected call of LastID.
func (mr *MockITransferMockRecorder) LastID(ctx any) *ITransferLastIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LastID", reflect.TypeOf((*MockITransfer)(nil).LastID), ctx)
	return &ITransferLastIDCall{Call: call}
}

// ITransferLastIDCall wrap *gomock.Call
type ITransferLastIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *ITransferLastIDCall) Return(arg0 uint64, arg1 error) *ITransferLastIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *ITransferLastIDCall) Do(f func(context.Context) (uint64, error)) *ITransferLastIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *ITransferLastIDCall) DoAndReturn(f func(context.Context) (uint64, error)) *ITransferLastIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// List mocks base method.
func (m *MockITransfer) List(ctx context.Context, limit, offset uint64, order storage0.SortOrder) ([]*storage.Transfer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, limit, offset, order)
	ret0, _ := ret[0].([]*storage.Transfer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockITransferMockRecorder) List(ctx, limit, offset, order any) *ITransferListCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockITransfer)(nil).List), ctx, limit, offset, order)
	return &ITransferListCall{Call: call}
}

// ITransferListCall wrap *gomock.Call
type ITransferListCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *ITransferListCall) Return(arg0 []*storage.Transfer, arg1 error) *ITransferListCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *ITransferListCall) Do(f func(context.Context, uint64, uint64, storage0.SortOrder) ([]*storage.Transfer, error)) *ITransferListCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *ITransferListCall) DoAndReturn(f func(context.Context, uint64, uint64, storage0.SortOrder) ([]*storage.Transfer, error)) *ITransferListCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Save mocks base method.
func (m_2 *MockITransfer) Save(ctx context.Context, m *storage.Transfer) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "Save", ctx, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockITransferMockRecorder) Save(ctx, m any) *ITransferSaveCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockITransfer)(nil).Save), ctx, m)
	return &ITransferSaveCall{Call: call}
}

// ITransferSaveCall wrap *gomock.Call
type ITransferSaveCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *ITransferSaveCall) Return(arg0 error) *ITransferSaveCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *ITransferSaveCall) Do(f func(context.Context, *storage.Transfer) error) *ITransferSaveCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *ITransferSaveCall) DoAndReturn(f func(context.Context, *storage.Transfer) error) *ITransferSaveCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Update mocks base method.
func (m_2 *MockITransfer) Update(ctx context.Context, m *storage.Transfer) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "Update", ctx, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockITransferMockRecorder) Update(ctx, m any) *ITransferUpdateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockITransfer)(nil).Update), ctx, m)
	return &ITransferUpdateCall{Call: call}
}

// ITransferUpdateCall wrap *gomock.Call
type ITransferUpdateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *ITransferUpdateCall) Return(arg0 error) *ITransferUpdateCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *ITransferUpdateCall) Do(f func(context.Context, *storage.Transfer) error) *ITransferUpdateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *ITransferUpdateCall) DoAndReturn(f func(context.Context, *storage.Transfer) error) *ITransferUpdateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
